telegram_bot_token: "6123211362:A2fx2eHR2124tfuHBLKfLUnPALEcrcY" #change it
expiry_days: 90
default_user_password: "hel22lo"
plan_id: 1
maintenance: false

panel:
    url: "https://195.231.213.290" #example "google.com"
    max_users: 1500 # Doesnt work yet
    email: "a@b.com"
    password: "a@b.com"

 
